services:
  woodstock-indexer:
    build:
      context: ${ROOT_DIR}
      dockerfile: services/woodstock_indexer/Dockerfile.local
    command: sleep infinity
    env_file:
      - env_files/woodstock-indexer.env
    image: woodstock_indexer_local
  woodstock-server:
    build:
      context: ${ROOT_DIR}
      dockerfile: services/woodstock_server/Dockerfile.local
    command: sleep infinity
    env_file:
      - env_files/woodstock-server.env
    image: woodstock_server_local
    ports:
      - 8050:8050
  woodstock-ui:
    build:
      context: ${ROOT_DIR}
      dockerfile: services/woodstock_ui/Dockerfile.local
    command: sleep infinity
    env_file:
      - env_files/woodstock-ui.env
    ports:
      - 3003:3003
    image: woodstock_ui_local
