services:
  woodstock-indexer:
    volumes:
      - ${ROOT_DIR}/libs/woodstock:/app/libs/woodstock
  woodstock-server:
    volumes:
      - ${ROOT_DIR}/libs/woodstock:/app/libs/woodstock
  woodstock-ui:
    volumes:
      - ${ROOT_DIR}/services/woodstock_ui:/app/src
