services:
  woodstock-indexer:
    command: woodstock run-indexer
    environment:
      WOODSTOCK_FILE_STORAGE_TYPE: local
      WOODSTOCK_LOCAL_STORAGE_DIR: /app/data
      WOODSTOCK_DB_PATH: /app/data/woodstock.db
      WOODSTOCK_POLL_INTERVAL_SECONDS: "5"
    volumes:
      - ${WOODSTOCK_LOCAL_FS_DIR}:/app/data

  woodstock-server:
    command: woodstock run-server --host 0.0.0.0 --port 8050
    environment:
      WOODSTOCK_FILE_STORAGE_TYPE: local
      WOODSTOCK_LOCAL_STORAGE_DIR: /app/data
      WOODSTOCK_DB_PATH: /app/data/woodstock.db
    volumes:
      - ${WOODSTOCK_LOCAL_FS_DIR}:/app/data
