FROM node:18-alpine

# install dev pkg dependencies
RUN apk update && apk add \
    curl \
    fish \
    bash \
    nano

# Install just
RUN curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /usr/local/bin

WORKDIR /app/src