export COMPOSE_PROJECT_NAME := "woodstock_test"
export ROOT_DIR := `git rev-parse --show-toplevel`
export COMPOSE_DIR := justfile_directory() + "/docker"

import 'just/_build_images.just'
import 'just/_up.just'
import 'just/_down.just'
import 'just/_run_image.just'

# Compile .env.in templates into .env files
compile-env-files:
    python scripts/compile_env_files.py docker/env_files

# Build all images
build *args:
    @just _build_images "{{ args }}" "false"

# Start services
up *args:
    @just _up "{{ args }}" "false" "false"

# Stop services
down:
    @just _down "false" "false"

# Start localstack and wait until healthy (bucket is created by the init script)
setup:
    #!/usr/bin/env bash
    set -euox pipefail
    just _up localstack "false" "false" "true"
    echo "Waiting for localstack to be healthy..."
    until docker inspect --format='{{{{.State.Health.Status}}}}' woodstock_localstack_test | grep -q healthy; do
        sleep 1
    done
    echo "Localstack is healthy."

# Run woodstock-indexer once (--no-loop)
run-indexer:
    @just _run_image "woodstock-indexer" "false" "false" woodstock-indexer --no-loop

# Run the integration tests
test:
    #!/usr/bin/env bash
    set -euox pipefail
    set -a && source docker/env_files/woodstock-test-runner.env && set +a
    JUST_DIR="{{justfile_directory()}}" python -m pytest tests/ -v
